[ERROR] 2019-08-29 13:40:38,068 | /home/satish/Desktop/Project/frappe-bench/apps/frappe/frappe/app.py:
Site: test
Form Dict: {
 "cmd": "meeting.api.send_invitation_emails",
 "meeting": "meeting1"
}
Request Error
Traceback (most recent call last):
  File "/home/satish/Desktop/Project/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/satish/Desktop/Project/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/satish/Desktop/Project/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/satish/Desktop/Project/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/satish/Desktop/Project/frappe-bench/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/satish/Desktop/Project/frappe-bench/apps/meeting/meeting/api.py", line 18, in send_invitation_emails
    as_bulk=True
TypeError: sendmail() got an unexpected keyword argument 'as_bulk'
